### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fbchow** [jamesmishra/mysqldump-to-csv#3]
Fran-MacBook-Air:hw4 fran$ python mysqldump_to_csv.py data.sql
Traceback (most recent call last):
  File "mysqldump_to_csv.py", line 111, in <module>
    main()
  File "mysqldump_to_csv.py", line 105, in main
    if values_sanity_check(values):
  File "mysqldump_to_csv.py", line 29, in values_sanity_check
    assert values
AssertionError

What does this error mean? Is it because I'm reading in the wrong type of file. Thanks!

**Comment by sa7mon** [comment]
I'm getting this too. Not sure what the issue is

**Comment by mattlevan** [comment]
I'm getting this as well in my attempt to convert Crunchbase's 2013 Snapshot mysqldump (.sql) files. Any help is appreciated!

**Comment by pianomonology** [comment]
I'm getting this problem right now.  Did anybody figure it out?
